import type { JudgeVerdict } from '../lib/api';
import { SectionTitle } from './Readouts';
import { C } from '../lib/theme';

/**
 * The LLM judge's reading of one situation — DISPLAY ONLY.
 *
 * Every string rendered here was written by a language model and arrives from
 * the server already labelled. This component computes nothing: no score is
 * averaged, no verdict is mapped to a word or a colour, no threshold is
 * applied. `verdict_label` and `verdict_tone` are server fields for exactly
 * that reason — a mapping table here would be the frontend forming its own
 * opinion about what a verdict means, and two screens would eventually
 * disagree about what the judge said.
 *
 * The banner is unconditional, following `ReplayPanel`'s `replay.label`: a
 * provenance notice behind a hover or a flag is a provenance notice that most
 * readers never see. What is being labelled matters here — a verdict is
 * commentary on whether the evidence supported a call, not a measurement of
 * anything, and not a validation of the decision engine.
 *
 * The judge was never shown what the driver actually did. This panel therefore
 * says nothing about `matches_recommendation`; that comparison lives in the
 * table, comes from `decision_service.historical_replay`, and is a different
 * question.
 */

const TONE: Record<string, string> = {
  ok: C.green, warn: C.amber, bad: C.red, neutral: C.gray,
};

const AXIS_ORDER = [
  'bracket_reporting', 'pass_model_honesty', 'gap_provenance',
  'affordability_and_value', 'confidence_calibration', 'refusal_discipline',
];

export function JudgePanel({ verdict, stale }:
  { verdict: JudgeVerdict | null; stale?: boolean }) {
  if (!verdict) {
    return (
      <div className="panel" style={{ padding: 15, color: C.dim, fontSize: 12.5,
                                      lineHeight: 1.65 }}>
        <SectionTitle>NO LLM VERDICT</SectionTitle>
        No language model has commented on this decision point. Verdicts are
        generated offline in batches, so most points do not have one.
      </div>
    );
  }

  const axes = AXIS_ORDER.filter((k) => verdict.axes?.[k]);

  return (
    <div className="panel" style={{ padding: 15 }}>
      <SectionTitle>LLM JUDGE</SectionTitle>

      <div style={{ padding: '8px 10px', borderRadius: 4, marginBottom: 10,
                    background: 'rgba(255,195,0,0.14)', color: C.amber,
                    fontSize: 11.5, fontWeight: 700, lineHeight: 1.5 }}>
        {verdict.label}
      </div>
      <div style={{ color: C.dim, fontSize: 11, lineHeight: 1.6,
                    marginBottom: 10 }}>
        Generated by {verdict.model_id}, prompt {verdict.prompt_version},
        rubric {verdict.rubric_version}. The judge was not shown what the driver
        did — it is grading whether the evidence supported the call, not whether
        the driver agreed.
      </div>

      {stale && (
        <div style={{ color: C.amber, fontSize: 11.5, lineHeight: 1.55,
                      marginBottom: 10 }}>
          This race was re-analysed after the verdict was written, so the
          commentary predates the numbers now on screen.
        </div>
      )}
      {verdict.judge_error && (
        <div style={{ color: C.red, fontSize: 11.5, lineHeight: 1.55,
                      marginBottom: 10 }}>
          Judge error: {verdict.judge_error}
        </div>
      )}

      <div style={{ color: TONE[verdict.verdict_tone] ?? C.gray, fontSize: 14,
                    fontWeight: 700, marginBottom: 4 }}>
        {verdict.verdict_label}
      </div>
      <div style={{ color: C.gray, fontSize: 12.5, lineHeight: 1.65 }}>
        {verdict.summary}
      </div>
      <div style={{ color: C.dim, fontSize: 11, marginTop: 6 }}>
        judge confidence {verdict.judge_confidence} · {verdict.n_turns} turns ·
        {' '}{verdict.tool_calls?.length ?? 0} tool calls
      </div>

      {verdict.abstained && verdict.abstain_reason && (
        <div style={{ color: C.amber, fontSize: 12, lineHeight: 1.6,
                      marginTop: 10 }}>
          Abstained: {verdict.abstain_reason}
        </div>
      )}

      {axes.length > 0 && (
        <div style={{ marginTop: 13 }}>
          <SectionTitle>RUBRIC</SectionTitle>
          {axes.map((k) => {
            const ax = verdict.axes[k];
            return (
              <div key={k} style={{ borderTop: `1px solid ${C.grid}`,
                                    padding: '7px 0' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between',
                              gap: 10 }}>
                  <span style={{ color: C.white, fontSize: 12 }}>{k}</span>
                  <span className="num" style={{ fontSize: 12, fontWeight: 700,
                                                 color: C.gray }}>
                    {ax.score}
                  </span>
                </div>
                <div style={{ color: C.gray, fontSize: 11.5, lineHeight: 1.55,
                              marginTop: 3 }}>
                  {ax.note}
                </div>
                {ax.evidence_refs?.length > 0 && (
                  <div style={{ color: C.dim, fontSize: 10.5, marginTop: 3 }}>
                    {ax.evidence_refs.join(' · ')}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      <div style={{ marginTop: 13 }}>
        <SectionTitle>FLAGGED</SectionTitle>
        {verdict.overclaims?.length ? verdict.overclaims.map((o, i) => (
          <div key={i} style={{ borderTop: `1px solid ${C.grid}`,
                                padding: '7px 0' }}>
            <div style={{ color: C.amber, fontSize: 12 }}>{o.field}</div>
            <div style={{ color: C.gray, fontSize: 11.5, lineHeight: 1.55 }}>
              {o.claim}
            </div>
            <div style={{ color: C.dim, fontSize: 11.5, lineHeight: 1.55,
                          marginTop: 2 }}>
              {o.why_wrong}
            </div>
          </div>
        )) : (
          <div style={{ color: C.dim, fontSize: 12 }}>
            No over-claims flagged.
          </div>
        )}
      </div>
    </div>
  );
}
